name: Deploy to DockerHub 2
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

      #      - run: yarn install
      #      - run: yarn nx run turn-tracker-backend:build:production
      - run: docker build . --file ./Dockerfile --tag abakholdin/turn-tracker-backend:latest
      - run: docker tag abakholdin/turn-tracker-backend:latest abakholdin/turn-tracker-backend:$(date +%s)
      - run: docker push abakholdin/turn-tracker-backend -a
