name: Deploy to DockerHub
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn install

      - name: Build Backend
        run: yarn nx run turn-tracker-backend:build:production
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./dist/apps/turn-tracker-backend
          file: ./apps/turn-tracker-backend/Dockerfile
          tags: ${{ secrets.DOCKER_USER }}/turn-tracker-backend:latest
          push: true


      - name: Build Frontend
        run: yarn nx run turn-tracker-spa:build:production
      - name: Upload Frontend
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USER}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: ./dist/apps/turn-tracker-spa/
          dangerous-clean-state: true
