name: Deploy to DockerHub
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #      - run: yarn install
      #      - run: yarn nx run turn-tracker-backend:build:production
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          #file: { context }/apps/turn-tracker-backend/Dockerfile
          tags: abakholdin/turn-tracker-backend:latest
          push: true
